### PR TITLE
Adding .deb package

### PR DESCRIPTION
**Pull request by devAmoghS**

### CODE REVIEW

**Comment by devAmoghS** [comment]
@GhostofGoes Created the PR.

**Comment by GhostofGoes** [comment]
How did you build this? When a new version is released, how would a new package be built?

**Comment by devAmoghS** [comment]
I pulled the source and used this link to create the build
https://www.tldp.org/HOWTO/html_single/Debian-Binary-Package-Building-HOWTO/

Okay , understood what you are pointing at. There should be a script to build the package every time a version is released, correct ?

**Comment by GhostofGoes** [comment]
Yes, there should be a script.

**Pull request closed without merging**
